# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json

roles:
  - name: geerlingguy.docker
    version: 7.7.0
  - name: geerlingguy.nfs
    version: 2.1.1
  - name: geerlingguy.ntp
    version: 3.0.0
  - name: geerlingguy.pip
    version: 3.1.1
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.containerd
    version: 1.4.1
  - name: bodsch.snapd
    version: 1.4.0
collections:
  - name: prometheus.prometheus
    version: 0.27.4
  - name: git+https://github.com/Penagwin/community.healthchecksio.git,main
    version: 1.3.1
